### PR TITLE
Few small changes...

### PR DESCRIPTION
**Pull request by ackackack**
Put more random on the hostname length
Made iptables rules extra hard

### CODE REVIEW

**Comment by tobykurien** [comment]
Thanks for the PR! I tested the changes but they don't seem to work:

- The hostname is now always 3 characters
- Internet access no longer works, can't even get DNS requests through

**Comment by tobykurien** [comment]
Thanks! I tested the changes but I can not longer resolve DNS requests, with or without the internet group.

**Comment by ackackack** [comment]
Yes this is correct behaviour.
I changed the policy from "allow" to a default "drop"
this catches all traffic from any program including those that can make dns and icmp packets.

ICMP and DNS can be used as a way of extracting data from a system ( see things like dns tunnel )

By doing this you have to knowingly allow these things through the firewall when you need them instead of allowing them to escape through convenience.

**Comment by tobykurien** [comment]
I agree that DNS and ICMP should also be blocked. However, using your changes, I am unable to get internet access at all. DNS never works. For some reason, DNS requests do not seem to be associated with an owner group id the way TCP packets are.

A solution might be to limit DNS packets to only the IP addresses found in `/etc/resolv.conf`. That would prevent DNS tunneling.

**Comment by ackackack** [comment]
Your idea should work here. 
You could get these details from resolv.conf. only trouble is that these details wouldn't be present/accurate until the network has come up and with the drop policy in place from the get go its likely things like DHCP wont work.
Bit of a catch 22 situation for auto configuration.

I'd have to confer with others and do a bit of research on this but i'm doubtful if the dns requests would be stamped with the users group anyway because dns lookups are generally performed via various C library calls which route it through the necessary mechanisms which then go on to perform the lookups. This, i think, is called the "resolver library"
also see: http://www.beej.us/guide/bgnet/output/html/singlepage/bgnet.html#getaddrinfo for the actual C functions used to call it. 

where as (for sake of an example) firefox will be running as a user with groups which may go on to directly open a socket to go and get that web page.

**Pull request merged**
